name: Cross compile for Windows
on:
  - push
  - pull_request
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        run: |
          sudo apt update
          sudo apt install -y gcc-mingw-w64-i686-win32

      - name: Load Pidgin from cache
        id: pidgin-cache
        uses: actions/cache@v4
        with:
          path: pidgin
          key: pidgin-2.10.11
      
      - name: Download Pidgin
        if: steps.pidgin-cache.outputs.cache-hit != 'true'
        run: |
          curl --http1.1 -L https://sourceforge.net/projects/pidgin/files/Pidgin/2.10.11/pidgin-2.10.11.tar.bz2/download -o pidgin.tar.bz2
          tar -xf pidgin.tar.bz2
          mv pidgin-2.10.11 pidgin
          curl --http1.1 -L https://sourceforge.net/projects/pidgin/files/Pidgin/2.10.11/pidgin-2.10.11-win32-bin.zip/download -o pidgin-win32bin.zip
          unzip pidgin-win32bin.zip
          cp pidgin-2.10.11-win32bin/libpurple.dll pidgin/libpurple/
      
      - name: Load Win32 deps from cache
        id: win32-cache
        uses: actions/cache@v4
        with:
          path: win32-dev
          key: win32-cache
      
      - name: Setup WinPidgin build
        if: steps.win32-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p win32-dev
          curl --http1.1 -L https://download.gnome.org/binaries/win32/glib/2.28/glib-dev_2.28.8-1_win32.zip -o glib-dev.zip
          unzip glib-dev.zip -d win32-dev/glib-2.28.8
          curl --http1.1 -L https://download.gnome.org/binaries/win32/dependencies/gettext-runtime-dev_0.18.1.1-2_win32.zip -o gettext-runtime.zip
          unzip gettext-runtime.zip -d win32-dev/glib-2.28.8
          curl --http1.1 -L https://download.gnome.org/binaries/win32/dependencies/zlib-dev_1.2.5-2_win32.zip -o zlib-dev.zip
          unzip zlib-dev.zip -d win32-dev/glib-2.28.8
          cd win32-dev
          curl --http1.1 -L https://github.com/jgeboski/purple-facebook/releases/download/downloads/json-glib-0.14.tar.gz -o json-glib.tar.gz
          tar -xf json-glib.tar.gz
          rm json-glib.tar.gz
          cd ..
          ls win32-dev/
      
      - name: libdiscount build
        run: |
          cd win32-dev
          curl --http1.1 -L https://github.com/Orc/discount/archive/refs/tags/2.2.1.tar.gz -o discount.tar.gz
          tar -xf discount.tar.gz
          rm discount.tar.gz
          cd discount-*
          ./configure.sh
          export CC=i686-w64-mingw32-gcc
          echo "#ifndef __AC_MARKDOWN_D" > config.h
          echo "#define __AC_MARKDOWN_D 1" >> config.h
          echo "#define OS_CYGWIN_NT 1" >> config.h
          echo "#define THEME_CF 1" >> config.h
          echo "#define while(x) while( (x) != 0 )" >> config.h
          echo "#define if(x) if( (x) != 0 )" >> config.h
          echo "#define DWORD unsigned long" >> config.h
          echo "#define WORD unsigned short" >> config.h
          echo "#define BYTE unsigned char" >> config.h
          echo "#define HAVE_STDLIB_H 1" >> config.h
          echo "#define HAVE_SRAND 1" >> config.h
          echo "#define INITRNG(x) srand((unsigned int)x)" >> config.h
          echo "#define HAVE_BZERO 1" >> config.h
          echo "#define HAVE_RAND 1" >> config.h
          echo "#define COINTOSS() (rand()&1)" >> config.h
          echo "#define HAVE_STRCASECMP 1" >> config.h
          echo "#define HAVE_STRNCASECMP 1" >> config.h
          echo "#define HAVE_GETCWD 1" >> config.h
          echo "#define TABSTOP 4" >> config.h
          echo "#define HAVE_MALLOC_H 1" >> config.h
          echo "#define PATH_FIND \"/usr/bin/find\"" >> config.h
          echo "#define PATH_SED \"/usr/bin/sed\"" >> config.h
          echo "#endif/* __AC_MARKDOWN_D */" >> config.h
          make libmarkdown
          rm libmarkdown.a
          i686-w64-mingw32-ar crv libmarkdown.a *.o
          i686-w64-mingw32-ranlib libmarkdown.a

      - name: make
        run: |
          export WIN32_CC=i686-w64-mingw32-gcc
          export WIN32_DEV_TOP=win32-dev
          export PIDGIN_TREE_TOP=pidgin
          export OS=Windows_NT
          make librocketchat.dll

      - name: archive
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with: 
            name: plugin 
            path: lib*.dll

      - name: release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !env.ACT
        uses: ncipollo/release-action@v1
        with:
          artifacts: lib*.dll
          tag: nightly-${{ github.sha }}
          name: Nightly ${{ github.sha }}
          allowUpdates: true
          makeLatest: true

      - name: attest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !env.ACT
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: lib*.dll
